name: "oura_analytics"
version: "1.0"
config-version: 2

profile: "oura_duckdb"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  oura_analytics:
    +materialized: table
    staging:
      +schema: "oura_staging"
    marts:
      +schema: "oura_marts"